[workspace]

resolver = "2"

members = [
    "crates/demo",
    "crates/error_demo",
    "crates/generics_demo",
    "crates/grrs",
    "crates/life_time",
    "crates/minigrep",
    "crates/ownership_demo"
, "crates/thread_demo"]
