[workspace]

resolver = "2"

members = [
    "crates/demo",
    "crates/error_demo",
    "crates/generics_demo",
    "crates/grrs",
    "crates/hello-async",
    "crates/life_time",
    "crates/minigrep",
    "crates/oop_demo",
    "crates/ownership_demo",
    "crates/thread_demo"
]
